In [1]:
!pip install mlflow dagshub optuna

Collecting mlflow
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting dagshub
  Downloading dagshub-0.6.8-py3-none-any.whl.metadata (12 kB)
Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Collecting mlflow-skinny==3.10.1 (from mlflow)
  Downloading mlflow_skinny-3.10.1-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.1 (from mlflow)
  Downloading mlflow_tracing-3.10.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<26 (from mlflow)
  Downloading gunicorn-25.1.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.47)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading databricks_sdk-0.96.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.133.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (26.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.41.0)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Collecting dataclasses-json (from dagshub)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Collecting boto3 (from dagshub)
  Downloading boto3-1.42.63-py3-none-any.whl.metadata (6.7 kB)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.1.12 (from dagshub)
  Downloading dagshub_annotation_converter-0.1.16-py3-none-any.whl.metadata (3.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (6.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.12)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.19.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Collecting botocore<1.43.0,>=1.42.63 (from boto3->dagshub)
  Downloading botocore-1.42.63-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->dagshub)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3->dagshub)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->dagshub)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->dagshub)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.22.0)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (5.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.4.4)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (0.4.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.6.2)
Downloading mlflow-3.10.1-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 33.4 MB/s eta 0:00:00
Downloading mlflow_skinny-3.10.1-py3-none-any.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 49.1 MB/s eta 0:00:00
Downloading mlflow_tracing-3.10.1-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 35.8 MB/s eta 0:00:00
Downloading dagshub-0.6.8-py3-none-any.whl (263 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.5/263.5 kB 8.5 MB/s eta 0:00:00
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 14.9 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.1.16-py3-none-any.whl (35 kB)
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 8.5 MB/s eta 0:00:00
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 6.1 MB/s eta 0:00:00
Downloading gunicorn-25.1.0-py3-none-any.whl (197 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.1/197.1 kB 10.7 MB/s eta 0:00:00
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 4.5 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.2/131.2 kB 7.8 MB/s eta 0:00:00
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading boto3-1.42.63-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 5.8 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading botocore-1.42.63-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 31.8 MB/s eta 0:00:00
Downloading databricks_sdk-0.96.0-py3-none-any.whl (813 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 814.0/814.0 kB 31.2 MB/s eta 0:00:00
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 13.5 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 2.5 MB/s eta 0:00:00
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 4.5 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 3.6 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: huey, appdirs, treelib, semver, pathvalidate, mypy-extensions, marshmallow, jmespath, gunicorn, graphql-core, dacite, colorlog, backoff, typing-inspect, graphql-relay, gql, docker, botocore, skops, s3transfer, optuna, graphene, Flask-CORS, dataclasses-json, databricks-sdk, dagshub-annotation-converter, boto3, mlflow-tracing, mlflow-skinny, dagshub, mlflow
Successfully installed Flask-CORS-6.0.2 appdirs-1.4.4 backoff-2.2.1 boto3-1.42.63 botocore-1.42.63 colorlog-6.10.1 dacite-1.6.0 dagshub-0.6.8 dagshub-annotation-converter-0.1.16 databricks-sdk-0.96.0 dataclasses-json-0.6.7 docker-7.1.0 gql-4.0.0 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 gunicorn-25.1.0 huey-2.6.0 jmespath-1.1.0 marshmallow-3.26.2 mlflow-3.10.1 mlflow-skinny-3.10.1 mlflow-tracing-3.10.1 mypy-extensions-1.1.0 optuna-4.7.0 pathvalidate-3.3.1 s3transfer-0.16.0 semver-3.0.4 skops-0.13.0 treelib-1.8.0 typing-inspect-0.9.0

In [4]:
import numpy as np
import pandas as pd
import utils_data_clean_preprocessed
import mlflow
import optuna
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,StackingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [5]:
import dagshub
dagshub.init(repo_owner='Iamkartikey44', repo_name='Food_Delivery_Time_Prediction', mlflow=True)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=e57256f3-96c3-4a76-b590-9e211975f661&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=5c4fbb1e3882fe108eaeb546a6d074268aca7809bd6166f8594d6ab4eccfd63f

Accessing as Iamkartikey44

Initialized MLflow to track repo "Iamkartikey44/Food_Delivery_Time_Prediction"

Repository Iamkartikey44/Food_Delivery_Time_Prediction initialized!

In [6]:
#Mlflow Experiment
mlflow.set_experiment("Exp3 - Stacking Regressor")

<Experiment: artifact_location='mlflow-artifacts:/4529f492c53e494cac2d43155358eb44', creation_time=1772964048951, experiment_id='2', last_update_time=1772964048951, lifecycle_stage='active', name='Exp3 - Stacking Regressor', tags={}, workspace='default'>

In [7]:
from sklearn import set_config
set_config(transform_output='pandas')

In [8]:
#Load the data
df = pd.read_csv("swiggy.csv")

In [9]:
#Load the clean data
df1 = utils_data_clean_preprocessed.perform_data_cleaning(df)

In [10]:
df1.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,0.0,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,0.0,short
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,0.0,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,0.0,short
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,0.0,short

In [11]:
df1.columns

Index(['age', 'ratings', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'is_weekend', 'pickup_time_minutes',
       'order_time_of_day', 'distance', 'distance_type'],
      dtype='object')

In [12]:
df1.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [13]:
df1.duplicated().sum()

np.int64(24)

In [14]:
temp_df = df1.copy()

In [15]:
# split into X and y

X = temp_df.drop(columns='time_taken')
y = temp_df['time_taken']

In [16]:
#Train Test Split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print(f"The size of train data is: {X_train.shape}")
print(f"The shape of test data is: {X_test.shape}")

The size of train data is: (30156, 15)
The shape of test data is: (7539, 15)

In [18]:
# missing values in train data
X_train.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [19]:
#Transform target column
pt = PowerTransformer()

y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

## Pre Processing Pipeline

In [20]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [21]:
#Generate order for ordinal encoding
traffic_order = ['low','medium','high','jam']
distance_type_order = ['short','medium','long','very_long']

In [22]:
# unique categories the ordinal columns
for col in ordinal_cat_cols:
    print(col,X_train[col].unique())

traffic ['jam' 'medium' 'high' 'low']
distance_type ['short']
Categories (4, object): ['short' < 'medium' < 'long' < 'very_long']

In [23]:
# build a preprocessor
preprocessor = ColumnTransformer(transformers=[
    ("scale",MinMaxScaler(),num_cols),
    ("nominal_encode",OneHotEncoder(handle_unknown="ignore",drop='first',sparse_output=False),nominal_cat_cols),
    ('ordinal_encode',OrdinalEncoder(categories=[traffic_order,distance_type_order],encoded_missing_value=-999,handle_unknown='use_encoded_value',unknown_value=-1),ordinal_cat_cols)
],remainder='passthrough',n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

In [24]:
preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [25]:
# build the pipeline
processing_pipeline  = Pipeline(steps=[
    ("preprocess",preprocessor)
])

In [ ]:
processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                                   remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 encoded_missing_value=-999,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [26]:
#Data Preprocessing
X_train_trans = processing_pipeline.fit_transform(X_train)
X_test_trans = processing_pipeline.transform(X_test)

In [47]:
xgb_params = {'n_estimators': 415,
 'max_depth': 20,
 'learning_rate': 0.29263456258035475,
 'subsample': 0.8759669065136347,
 'colsample_bytree': 0.7213914971809194,
 'min_child_weight': 17,
 'gamma': 1.0059958323704052,
 'reg_lambda': 37.94112216359326,
 'reg_alpha': 0.5695261402488025}

lgbm_params ={'n_estimators': 398,
 'max_depth': 30,
 'learning_rate': 0.17723976615372525,
 'subsample': 0.6668154532640596,
 'min_child_weight': 13,
 'min_split_gain': 0.00042029710843746043,
 'reg_lambda': 75.85847527149905}

rf_params =  {'n_estimators': 500,
 'max_depth': 14,
 'max_features': None,
 'min_samples_split': 9,
 'min_samples_leaf': 6,
 'max_samples': 0.9797814656591307}

In [48]:
xgb_reg = XGBRegressor(**xgb_params)
lgbm_reg = LGBMRegressor(**lgbm_params)
rf_reg = RandomForestRegressor(**rf_params)

In [ ]:
# build the best models
best_rf_params = {'n_estimators': 479,
 'criterion': 'squared_error',
 'max_depth': 17,
 'max_features': None,
 'min_samples_split': 9,
 'min_samples_leaf': 2,
 'max_samples': 0.6603673526197067}

best_lgbm_params = {'n_estimators': 154,
 'max_depth': 27,
 'learning_rate': 0.22234435854395157,
 'subsample': 0.7592213724048168,
 'min_child_weight': 20,
 'min_split_gain': 0.004604680609280751,
 'reg_lambda': 97.81002379097947}

best_rf = RandomForestRegressor(**best_rf_params)
best_lgbm = LGBMRegressor(**best_lgbm_params)

In [49]:
def objective(trial):
  with mlflow.start_run(nested=True):
    meta_model_name = trial.suggest_categorical("model",["LR","KNN","DT"])

    if meta_model_name =='LR':
      meta = LinearRegression()

    elif meta_model_name =='KNN':
      n_neighbors = trial.suggest_int("n_neighbors",1,50)
      weights_knn = trial.suggest_categorical("weights_knn",["uniform","distance"])
      meta = KNeighborsRegressor(n_neighbors=n_neighbors,weights=weights_knn,n_jobs=-1)

    elif meta_model_name =='DT':
      max_depth_dt = trial.suggest_int("max_depth_dt",1,10)
      min_sample_split_dt = trial.suggest_int("min_samples_split_dt",2,10)
      min_samples_leaf_dt = trial.suggest_int("min_samples_leaf_dt",1,10)
      meta = DecisionTreeRegressor(max_depth=max_depth_dt,min_samples_split=min_sample_split_dt,min_samples_leaf=min_samples_leaf_dt,random_state=42)

    #Log meta model name
    mlflow.log_param("meta_model_name",meta_model_name)


    #Stacking regressor
    #stacking_reg = StackingRegressor(estimators=[('rf',best_rf),('lgbm',best_lgbm)],final_estimator=meta,cv=5,n_jobs=-1)
    stacking_reg = StackingRegressor(estimators=[('XGBoost',xgb_reg),('lgbm',lgbm_reg),('rf',rf_reg)],final_estimator=meta,cv=5,n_jobs=-1)

    #Build Transformed regressor
    model = TransformedTargetRegressor(regressor=stacking_reg,transformer=pt)

    #Train the model
    model.fit(X_train_trans,y_train)

    #Predict on test data
    y_pred_test = model.predict(X_test_trans)

    #Mean Absoulte error
    error = mean_absolute_error(y_test,y_pred_test)

    #Log Error
    mlflow.log_metric("MAE",error)

    return error

In [50]:
# create optuna study
study = optuna.create_study(direction='minimize')

with mlflow.start_run(run_name='best_model'):
  study.optimize(objective,n_trials=10,n_jobs=-1,show_progress_bar=True)
  mlflow.log_params(study.best_params)
  mlflow.log_metric("Best Score",study.best_value)

[I 2026-03-08 18:12:39,658] A new study created in memory with name: no-name-2d31d338-c9e7-4bb7-afa6-49460a563db6

  0%|          | 0/10 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run trusting-lynx-617 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/aca88dc712414d0ea1338f88ac499442
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:16:54,805] Trial 0 finished with value: 3.709892764117285 and parameters: {'model': 'LR'}. Best is trial 0 with value: 3.709892764117285.
🏃 View run calm-hog-352 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/f6b77ec6fc2646a8a023f1a29a543bb2
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:17:13,655] Trial 1 finished with value: 3.744727575153803 and parameters: {'model': 'DT', 'max_depth_dt': 4, 'min_samples_split_dt': 7, 'min_samples_leaf_dt': 5}. Best is trial 0 with value: 3.709892764117285.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run shivering-deer-361 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/1bcf5b212acb47ebbe28a057b3bb9c7b
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:21:17,573] Trial 2 finished with value: 4.209203476802627 and parameters: {'model': 'DT', 'max_depth_dt': 2, 'min_samples_split_dt': 2, 'min_samples_leaf_dt': 4}. Best is trial 0 with value: 3.709892764117285.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run auspicious-wasp-374 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/c0a057c83a994b6a84b92bd6edae4e96
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:21:33,591] Trial 3 finished with value: 4.206727408371285 and parameters: {'model': 'DT', 'max_depth_dt': 2, 'min_samples_split_dt': 9, 'min_samples_leaf_dt': 10}. Best is trial 0 with value: 3.709892764117285.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run loud-panda-624 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/64d90b5c013247dab81510de5fab0f33
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:25:39,708] Trial 4 finished with value: 4.287808092053279 and parameters: {'model': 'KNN', 'n_neighbors': 3, 'weights_knn': 'distance'}. Best is trial 0 with value: 3.709892764117285.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run silent-ram-310 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/96cfced0e70544f0a1d94fe0dbcf2f2f
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:25:54,512] Trial 5 finished with value: 3.709082919049857 and parameters: {'model': 'LR'}. Best is trial 5 with value: 3.709082919049857.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run charming-calf-349 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/41a3ec0c87354caa9a7b5078e8aeb62b
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:29:59,404] Trial 6 finished with value: 3.709899482669589 and parameters: {'model': 'LR'}. Best is trial 5 with value: 3.709082919049857.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run masked-shoat-705 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/d772382e48614b95a2893bc9e189dc43
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:30:16,994] Trial 7 finished with value: 3.8447189074946797 and parameters: {'model': 'DT', 'max_depth_dt': 3, 'min_samples_split_dt': 2, 'min_samples_leaf_dt': 6}. Best is trial 5 with value: 3.709082919049857.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run bold-cub-446 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/0361fa2609b842ae81919ee77b2b8afc
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:34:19,646] Trial 8 finished with value: 3.7091299555032022 and parameters: {'model': 'LR'}. Best is trial 5 with value: 3.709082919049857.
🏃 View run learned-fish-680 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/9b0a8d0be6644fe0846ed594f5be5bf1
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2
[I 2026-03-08 18:34:31,880] Trial 9 finished with value: 5.20285833244446 and parameters: {'model': 'DT', 'max_depth_dt': 1, 'min_samples_split_dt': 5, 'min_samples_leaf_dt': 2}. Best is trial 5 with value: 3.709082919049857.
🏃 View run best_model at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2/runs/50da63a128254c83b22be36bd632275c
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/2

In [45]:
# best parameter value
best_params = study.best_params
best_params

{'model': 'LR'}

In [44]:
# parameter value counts
study.trials_dataframe()["params_model"].value_counts()

params_model
DT     5
KNN    3
LR     2
Name: count, dtype: int64

In [46]:
# mean scores for each meta estimator type
study.trials_dataframe().groupby(by="params_model")['value'].mean().sort_values()

params_model
LR     3.710389
DT     3.861742
KNN    3.865330
Name: value, dtype: float64

In [ ]:
# mean scores for each meta estimator type
study.trials_dataframe().groupby(by="params_model")['value'].mean().sort_values()

params_model
LR     3.721409
KNN    3.950509
DT     3.999897
Name: value, dtype: float64

In [51]:
study.best_value

3.709082919049857

In [41]:
study.best_value #3M

3.710187360655401

In [32]:
# best score
study.best_value

3.73268421566814

In [ ]:
# best score
study.best_value

3.7194792641423384

In [53]:
# optimization history plot
optuna.visualization.plot_optimization_history(study)

In [54]:
# parallel coord plot
optuna.visualization.plot_parallel_coordinate(study,params=["model"])