In [1]:
!pip install mlflow dagshub optuna

Collecting mlflow
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting dagshub
  Downloading dagshub-0.6.8-py3-none-any.whl.metadata (12 kB)
Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Collecting mlflow-skinny==3.10.1 (from mlflow)
  Downloading mlflow_skinny-3.10.1-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.1 (from mlflow)
  Downloading mlflow_tracing-3.10.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<26 (from mlflow)
  Downloading gunicorn-25.1.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.47)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading databricks_sdk-0.96.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.133.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (26.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.41.0)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Collecting dataclasses-json (from dagshub)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Collecting boto3 (from dagshub)
  Downloading boto3-1.42.63-py3-none-any.whl.metadata (6.7 kB)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.1.12 (from dagshub)
  Downloading dagshub_annotation_converter-0.1.16-py3-none-any.whl.metadata (3.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (6.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.12)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.19.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Collecting botocore<1.43.0,>=1.42.63 (from boto3->dagshub)
  Downloading botocore-1.42.63-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->dagshub)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3->dagshub)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->dagshub)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->dagshub)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.22.0)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (5.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.4.4)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (0.4.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.6.2)
Downloading mlflow-3.10.1-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 84.9 MB/s eta 0:00:00
Downloading mlflow_skinny-3.10.1-py3-none-any.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 56.3 MB/s eta 0:00:00
Downloading mlflow_tracing-3.10.1-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 45.0 MB/s eta 0:00:00
Downloading dagshub-0.6.8-py3-none-any.whl (263 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.5/263.5 kB 18.8 MB/s eta 0:00:00
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 29.1 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.1.16-py3-none-any.whl (35 kB)
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 14.1 MB/s eta 0:00:00
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 12.5 MB/s eta 0:00:00
Downloading gunicorn-25.1.0-py3-none-any.whl (197 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.1/197.1 kB 20.9 MB/s eta 0:00:00
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 7.3 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.2/131.2 kB 14.6 MB/s eta 0:00:00
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading boto3-1.42.63-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 14.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading botocore-1.42.63-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 91.0 MB/s eta 0:00:00
Downloading databricks_sdk-0.96.0-py3-none-any.whl (813 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 814.0/814.0 kB 52.5 MB/s eta 0:00:00
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 19.7 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 4.7 MB/s eta 0:00:00
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.6 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 8.6 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: huey, appdirs, treelib, semver, pathvalidate, mypy-extensions, marshmallow, jmespath, gunicorn, graphql-core, dacite, colorlog, backoff, typing-inspect, graphql-relay, gql, docker, botocore, skops, s3transfer, optuna, graphene, Flask-CORS, dataclasses-json, databricks-sdk, dagshub-annotation-converter, boto3, mlflow-tracing, mlflow-skinny, dagshub, mlflow
Successfully installed Flask-CORS-6.0.2 appdirs-1.4.4 backoff-2.2.1 boto3-1.42.63 botocore-1.42.63 colorlog-6.10.1 dacite-1.6.0 dagshub-0.6.8 dagshub-annotation-converter-0.1.16 databricks-sdk-0.96.0 dataclasses-json-0.6.7 docker-7.1.0 gql-4.0.0 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 gunicorn-25.1.0 huey-2.6.0 jmespath-1.1.0 marshmallow-3.26.2 mlflow-3.10.1 mlflow-skinny-3.10.1 mlflow-tracing-3.10.1 mypy-extensions-1.1.0 optuna-4.7.0 pathvalidate-3.3.1 s3transfer-0.16.0 semver-3.0.4 skops-0.13.0 treelib-1.8.0 typing-inspect-0.9.0

In [2]:
import numpy as np
import pandas as pd
import utils_data_clean_preprocessed
import mlflow
import optuna
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,StackingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [5]:
import dagshub
dagshub.init(repo_owner='Iamkartikey44', repo_name='Food_Delivery_Time_Prediction', mlflow=True)

Initialized MLflow to track repo "Iamkartikey44/Food_Delivery_Time_Prediction"

Repository Iamkartikey44/Food_Delivery_Time_Prediction initialized!

In [6]:
#Mlflow Experiment
mlflow.set_experiment("Exp4 - XGBoost_LGBM_RF HP")

2026/03/08 17:09:22 INFO mlflow.tracking.fluent: Experiment with name 'Exp4 - XGBoost_LGBM_RF HP' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/1449875d257643b9ac5ee2ed2142acc5', creation_time=1772989762543, experiment_id='4', last_update_time=1772989762543, lifecycle_stage='active', name='Exp4 - XGBoost_LGBM_RF HP', tags={}, workspace='default'>

In [7]:
from sklearn import set_config
set_config(transform_output='pandas')

In [8]:
#Load the clean data
df = pd.read_csv("swiggy.csv")

In [9]:
#Load the clean data
df1 = utils_data_clean_preprocessed.perform_data_cleaning(df)

In [10]:
df1.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,0.0,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,0.0,short
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,0.0,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,0.0,short
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,0.0,short

In [11]:
df1.columns

Index(['age', 'ratings', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'is_weekend', 'pickup_time_minutes',
       'order_time_of_day', 'distance', 'distance_type'],
      dtype='object')

In [12]:
df1.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
time_taken             0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [13]:
df1.duplicated().sum()

np.int64(24)

In [14]:
temp_df= df1.copy()

In [15]:
# split into X and y

X = temp_df.drop(columns='time_taken')
y = temp_df['time_taken']

In [16]:
#Train Test Split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print(f"The size of train data is: {X_train.shape}")
print(f"The shape of test data is: {X_test.shape}")

The size of train data is: (30156, 15)
The shape of test data is: (7539, 15)

In [18]:
#Transform Target Column
pt = PowerTransformer()
y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

In [19]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [20]:
# generate order for ordinal encoding
traffic_order = ["low","medium","high","jam"]
distance_type_order = ["short","medium","long","very_long"]

In [21]:
# unique categories the ordinal columns
for col in ordinal_cat_cols:
    print(col,X_train[col].unique())

traffic ['jam' 'medium' 'high' 'low']
distance_type ['short']
Categories (4, object): ['short' < 'medium' < 'long' < 'very_long']

In [22]:
#Build a preprocessor
preprocessor = ColumnTransformer(transformers=[
    ("scale",MinMaxScaler(),num_cols),
    ('nominal_encode',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False),nominal_cat_cols),
    ("ordinal_encode",OrdinalEncoder(categories=[traffic_order,distance_type_order],encoded_missing_value=-999,handle_unknown='use_encoded_value',unknown_value=-1),ordinal_cat_cols)
],remainder='passthrough',n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

In [ ]:
preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [23]:
# build the pipeline

processing_pipeline = Pipeline(steps=[("preprocess",preprocessor)])
processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                                   remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 encoded_missing_value=-999,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [24]:
X_train_trans = processing_pipeline.fit_transform(X_train)
X_test_trans = processing_pipeline.transform(X_test)

In [26]:
def objective(trial):

    with mlflow.start_run(nested=True):

        params = {
            "n_estimators": trial.suggest_int("n_estimators", 10, 500),
            "max_depth": trial.suggest_int("max_depth", 1, 30),

            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.8),

            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),

            "min_child_weight": trial.suggest_int("min_child_weight", 5, 20),

            "gamma": trial.suggest_float("gamma", 0, 10),

            "reg_lambda": trial.suggest_float("reg_lambda", 0, 100),
            "reg_alpha": trial.suggest_float("reg_alpha", 0, 100),

            "random_state": 42,
            "n_jobs": -1
        }

        mlflow.log_params(params)

        xgb_reg = XGBRegressor(**params)

        model = TransformedTargetRegressor(
            regressor=xgb_reg,
            transformer=pt
        )

        model.fit(X_train_trans, y_train)

        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)

        # cross validation
        cv_score = cross_val_score(
            model,
            X_train_trans,
            y_train,
            cv=5,
            scoring="neg_mean_absolute_error",
            n_jobs=1
        )

        mean_score = -cv_score.mean()

        mlflow.log_metric("cv_score", mean_score)

        return mean_score

In [27]:
study = optuna.create_study(direction='minimize')

with mlflow.start_run(run_name='best_model'):
  study.optimize(objective,n_trials=40,n_jobs=-1,show_progress_bar=True)
  mlflow.log_params(study.best_params)
  mlflow.log_metric("best_score",study.best_value)
  best_xgb = XGBRegressor(**study.best_params)
  best_xgb.fit(X_train_trans,y_train_pt.values.ravel())
  y_pred_train = best_xgb.predict(X_train_trans)
  y_pred_test = best_xgb.predict(X_test_trans)
  # get the actual predictions values
  y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
  y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))

  model = TransformedTargetRegressor(regressor=best_xgb,transformer=pt)
  scores = cross_val_score(model,X_train_trans,y_train,scoring='neg_mean_squared_error',cv=5,n_jobs=-1)
  #Log Metrics
  mlflow.log_metric("Training Error",mean_absolute_error(y_train,y_pred_train_org))
  mlflow.log_metric("Testing Error",mean_absolute_error(y_test,y_pred_test_org))
  mlflow.log_metric("Training R2",r2_score(y_train,y_pred_train_org))
  mlflow.log_metric("Testing R2",r2_score(y_test,y_pred_test_org))
  mlflow.log_metric("Cross Val Score",scores.mean())

  mlflow.sklearn.log_model(best_xgb,artifact_path="model")

[I 2026-03-08 17:14:04,505] A new study created in memory with name: no-name-118d0da7-1c18-4239-a5ec-9fabd8ab4a9e

  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run big-grouse-634 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/c247cea803a54a0eb196145726908707
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:08,738] Trial 1 finished with value: 6.605313110351562 and parameters: {'n_estimators': 23, 'max_depth': 3, 'learning_rate': 0.015106198690459649, 'subsample': 0.6474770821882603, 'colsample_bytree': 0.9046584716340274, 'min_child_weight': 19, 'gamma': 4.731630260422124, 'reg_lambda': 20.40331193686622, 'reg_alpha': 3.8583218570648503}. Best is trial 1 with value: 6.605313110351562.
🏃 View run flawless-cow-541 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/6c513d574b35425bbaef8d43ce84de4c
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:12,591] Trial 0 finished with value: 4.301612377166748 and parameters: {'n_estimators': 290, 'max_depth': 22, 'learning_rate': 0.6853621270501329, 'subsample': 0.5777193598582921, 'colsample_bytree': 0.8707635974878137, 'min_child_weight': 11, 'gamma': 2.7985075394008687, 'reg_lambda': 39.54024514872383, 'reg_alpha': 83.37546068145163}. Best is trial 0 with value: 4.301612377166748.
🏃 View run wise-lark-588 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/72b884d64bfd47f68cc00012aa69b28d
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:13,895] Trial 2 finished with value: 4.318193340301514 and parameters: {'n_estimators': 269, 'max_depth': 11, 'learning_rate': 0.6031929045366884, 'subsample': 0.7599535069606613, 'colsample_bytree': 0.7959445789653474, 'min_child_weight': 18, 'gamma': 7.990666450631691, 'reg_lambda': 99.23189504550741, 'reg_alpha': 68.01439022072715}. Best is trial 0 with value: 4.301612377166748.
🏃 View run crawling-donkey-997 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/9a238cd8b8384a959355b8d685b1abc5
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:17,872] Trial 4 finished with value: 4.697264003753662 and parameters: {'n_estimators': 153, 'max_depth': 1, 'learning_rate': 0.692593208957903, 'subsample': 0.5319987352165417, 'colsample_bytree': 0.6420023090729723, 'min_child_weight': 7, 'gamma': 8.131675895967764, 'reg_lambda': 0.8908015416246196, 'reg_alpha': 94.57482294490028}. Best is trial 0 with value: 4.301612377166748.
🏃 View run rumbling-stork-209 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/c24fdf0fc251435b8402debab3f141ed
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:21,958] Trial 3 finished with value: 4.149811840057373 and parameters: {'n_estimators': 364, 'max_depth': 23, 'learning_rate': 0.6641709406704843, 'subsample': 0.7132007204808253, 'colsample_bytree': 0.9541583739770905, 'min_child_weight': 12, 'gamma': 4.851781987657029, 'reg_lambda': 47.53105949514291, 'reg_alpha': 58.90305750914467}. Best is trial 3 with value: 4.149811840057373.
🏃 View run bedecked-hound-271 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/8f60cc58829e4e78a25654d4ad31697a
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:26,937] Trial 5 finished with value: 4.133952713012695 and parameters: {'n_estimators': 141, 'max_depth': 8, 'learning_rate': 0.7222290758196183, 'subsample': 0.6385229933167226, 'colsample_bytree': 0.75397395859307, 'min_child_weight': 12, 'gamma': 3.9503200342433376, 'reg_lambda': 8.927627139383453, 'reg_alpha': 21.01258421218546}. Best is trial 5 with value: 4.133952713012695.
🏃 View run loud-fawn-779 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/6d83cf19145e4114b2f0fc7af3d2b669
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:31,961] Trial 6 finished with value: 4.2927422523498535 and parameters: {'n_estimators': 99, 'max_depth': 8, 'learning_rate': 0.565481837922893, 'subsample': 0.9467340905467063, 'colsample_bytree': 0.849526739333631, 'min_child_weight': 5, 'gamma': 7.129829568467142, 'reg_lambda': 45.04416025308993, 'reg_alpha': 97.58043038279132}. Best is trial 5 with value: 4.133952713012695.
🏃 View run secretive-bee-162 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/30ef451bec6a45539ebe0327485ba774
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:36,948] Trial 8 finished with value: 4.280778503417968 and parameters: {'n_estimators': 16, 'max_depth': 11, 'learning_rate': 0.21062038304938172, 'subsample': 0.5524527846202705, 'colsample_bytree': 0.9700934711836544, 'min_child_weight': 19, 'gamma': 1.8288381464269365, 'reg_lambda': 90.6500646788136, 'reg_alpha': 65.31205890948948}. Best is trial 5 with value: 4.133952713012695.
🏃 View run sincere-smelt-669 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/358164526d7041fcb5d8eae780017ff4
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:41,955] Trial 7 finished with value: 4.2352289199829105 and parameters: {'n_estimators': 477, 'max_depth': 3, 'learning_rate': 0.36014558916488515, 'subsample': 0.5269532510245882, 'colsample_bytree': 0.8469734602417376, 'min_child_weight': 11, 'gamma': 0.4247549462168221, 'reg_lambda': 87.97397232788913, 'reg_alpha': 66.82650299437776}. Best is trial 5 with value: 4.133952713012695.
🏃 View run treasured-bee-124 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/d0d44a9fecff44f8819458caff2ffb6b
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:46,967] Trial 9 finished with value: 4.116434478759766 and parameters: {'n_estimators': 452, 'max_depth': 14, 'learning_rate': 0.49596217778665713, 'subsample': 0.9813441554815063, 'colsample_bytree': 0.6676895749729029, 'min_child_weight': 5, 'gamma': 5.002092003161476, 'reg_lambda': 59.46886719473648, 'reg_alpha': 30.778527163233036}. Best is trial 9 with value: 4.116434478759766.
🏃 View run righteous-foal-934 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/a66fa8fa16da49f39e977c84f9134cce
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:51,966] Trial 10 finished with value: 4.085258483886719 and parameters: {'n_estimators': 218, 'max_depth': 27, 'learning_rate': 0.7527139347156826, 'subsample': 0.6896414546493502, 'colsample_bytree': 0.8119654151365845, 'min_child_weight': 8, 'gamma': 1.4958723145495223, 'reg_lambda': 88.35793110840719, 'reg_alpha': 24.195825076778966}. Best is trial 10 with value: 4.085258483886719.
🏃 View run respected-steed-390 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/6adf826551914c68858255a33e9ea4ab
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:14:56,959] Trial 11 finished with value: 4.223161125183106 and parameters: {'n_estimators': 488, 'max_depth': 30, 'learning_rate': 0.4431491676384651, 'subsample': 0.9784439129542564, 'colsample_bytree': 0.5521191082665338, 'min_child_weight': 8, 'gamma': 6.39401760829831, 'reg_lambda': 70.83814585617856, 'reg_alpha': 34.934552812333905}. Best is trial 10 with value: 4.085258483886719.
🏃 View run judicious-jay-12 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/baf4aa212b38432b86f69faf46529c58
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:02,008] Trial 12 finished with value: 4.203927230834961 and parameters: {'n_estimators': 463, 'max_depth': 30, 'learning_rate': 0.47188981719053696, 'subsample': 0.9165518879560036, 'colsample_bytree': 0.631686453876323, 'min_child_weight': 8, 'gamma': 6.3323411921214845, 'reg_lambda': 71.73310445197929, 'reg_alpha': 33.497887959644295}. Best is trial 10 with value: 4.085258483886719.
🏃 View run ambitious-cow-408 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/680d2bc95de9474db96a7e26353cd842
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:06,963] Trial 13 finished with value: 4.036555194854737 and parameters: {'n_estimators': 379, 'max_depth': 19, 'learning_rate': 0.7877084665125962, 'subsample': 0.8385334295770486, 'colsample_bytree': 0.6774609354691049, 'min_child_weight': 5, 'gamma': 0.46619664727572085, 'reg_lambda': 64.5896783797983, 'reg_alpha': 37.99051300063941}. Best is trial 13 with value: 4.036555194854737.
🏃 View run bittersweet-gnu-106 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/19e1f8e4a77a48909ad2aa66e25f7a1e
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:11,956] Trial 14 finished with value: 4.167831230163574 and parameters: {'n_estimators': 363, 'max_depth': 17, 'learning_rate': 0.7860318259834961, 'subsample': 0.8375001630406841, 'colsample_bytree': 0.6786702176955883, 'min_child_weight': 5, 'gamma': 9.920995940696802, 'reg_lambda': 65.71645036455561, 'reg_alpha': 12.121423085537636}. Best is trial 13 with value: 4.036555194854737.
🏃 View run dashing-deer-785 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/2ae215153c4d4dcbb0310d3485415e86
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:17,527] Trial 15 finished with value: 3.912642478942871 and parameters: {'n_estimators': 355, 'max_depth': 22, 'learning_rate': 0.7882688949390033, 'subsample': 0.8400774196788883, 'colsample_bytree': 0.7088006517576045, 'min_child_weight': 16, 'gamma': 0.1919728303420435, 'reg_lambda': 75.45197803448586, 'reg_alpha': 5.714787424094624}. Best is trial 15 with value: 3.912642478942871.
🏃 View run popular-asp-117 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/aa963ebce1f342ad8baa13aa4ef9fd09
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:21,965] Trial 16 finished with value: 4.009090900421143 and parameters: {'n_estimators': 208, 'max_depth': 24, 'learning_rate': 0.7906934642099239, 'subsample': 0.8212750605735547, 'colsample_bytree': 0.7363124883944469, 'min_child_weight': 15, 'gamma': 0.09792574352701577, 'reg_lambda': 81.29746773432316, 'reg_alpha': 46.647705343547074}. Best is trial 15 with value: 3.912642478942871.
🏃 View run clean-mink-700 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/7cf74f4d1e414698bb0e5e8d4d0130fb
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:26,963] Trial 17 finished with value: 4.125924777984619 and parameters: {'n_estimators': 374, 'max_depth': 19, 'learning_rate': 0.3472454930832936, 'subsample': 0.8529246024499265, 'colsample_bytree': 0.5028288904212697, 'min_child_weight': 16, 'gamma': 0.7033772890020025, 'reg_lambda': 78.93740861143637, 'reg_alpha': 44.63242180983892}. Best is trial 15 with value: 3.912642478942871.
🏃 View run orderly-snail-389 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/a0a7cfeb9b1b4eb0a47d9ffa92043bd2
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:31,951] Trial 18 finished with value: 4.18292818069458 and parameters: {'n_estimators': 232, 'max_depth': 24, 'learning_rate': 0.2386890367223798, 'subsample': 0.815379960042271, 'colsample_bytree': 0.5163086322816893, 'min_child_weight': 16, 'gamma': 2.6538025748564156, 'reg_lambda': 79.20680123537028, 'reg_alpha': 53.06975839813841}. Best is trial 15 with value: 3.912642478942871.
🏃 View run abrasive-toad-236 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/f1b7a295b3d24b0dbbbf5ae9f3a6eb5e
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:36,965] Trial 19 finished with value: 3.851807641983032 and parameters: {'n_estimators': 209, 'max_depth': 25, 'learning_rate': 0.2213155927933314, 'subsample': 0.7834934595013936, 'colsample_bytree': 0.7233335465748578, 'min_child_weight': 15, 'gamma': 1.8752150496727387, 'reg_lambda': 28.130995601861432, 'reg_alpha': 0.4042517659167686}. Best is trial 19 with value: 3.851807641983032.
🏃 View run casual-vole-500 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/9460adf535d149378b1e379aad5edb7e
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:44,431] Trial 20 finished with value: 3.868425226211548 and parameters: {'n_estimators': 314, 'max_depth': 26, 'learning_rate': 0.5876461057029433, 'subsample': 0.8926046201788036, 'colsample_bytree': 0.727289399636766, 'min_child_weight': 15, 'gamma': 0.04839010940182831, 'reg_lambda': 33.220578449238886, 'reg_alpha': 10.597757212540476}. Best is trial 19 with value: 3.851807641983032.
🏃 View run dazzling-lark-469 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/7d058a3e341e4a279c483799d7008f02
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:46,977] Trial 21 finished with value: 3.897766923904419 and parameters: {'n_estimators': 311, 'max_depth': 26, 'learning_rate': 0.08407881399239522, 'subsample': 0.7659994559989171, 'colsample_bytree': 0.7460029226838841, 'min_child_weight': 14, 'gamma': 3.1226802304214214, 'reg_lambda': 26.347237594397715, 'reg_alpha': 0.03501101306007115}. Best is trial 19 with value: 3.851807641983032.
🏃 View run rare-sheep-969 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/9f16b74fe36d449abd2ba56b56d32a8e
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:52,131] Trial 22 finished with value: 3.8464348316192627 and parameters: {'n_estimators': 319, 'max_depth': 26, 'learning_rate': 0.12993965131249552, 'subsample': 0.8971213592210636, 'colsample_bytree': 0.7332037354005899, 'min_child_weight': 14, 'gamma': 1.7052300222817038, 'reg_lambda': 29.987210448941475, 'reg_alpha': 0.007319495667249987}. Best is trial 22 with value: 3.8464348316192627.
🏃 View run adorable-sloth-224 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/fe1804a9732b4705b57974e678592d74
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:15:56,951] Trial 23 finished with value: 3.9664337635040283 and parameters: {'n_estimators': 307, 'max_depth': 27, 'learning_rate': 0.0584869046531766, 'subsample': 0.7767141038785351, 'colsample_bytree': 0.7742183016300797, 'min_child_weight': 14, 'gamma': 3.216910328348829, 'reg_lambda': 32.13390826401273, 'reg_alpha': 12.951744416877723}. Best is trial 22 with value: 3.8464348316192627.
🏃 View run monumental-ram-803 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/0a12acdd10244f5e9f2c2755b2acea54
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:16:01,979] Trial 24 finished with value: 3.987108087539673 and parameters: {'n_estimators': 313, 'max_depth': 27, 'learning_rate': 0.17402751312490472, 'subsample': 0.9013630254396607, 'colsample_bytree': 0.5984008372857255, 'min_child_weight': 14, 'gamma': 1.6263540331475201, 'reg_lambda': 29.37493549890569, 'reg_alpha': 13.851065664288178}. Best is trial 22 with value: 3.8464348316192627.
🏃 View run adorable-goat-850 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/77be972953f14bc8bb0203a8ff63e3c9
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:16:06,956] Trial 25 finished with value: 3.9830862522125243 and parameters: {'n_estimators': 179, 'max_depth': 28, 'learning_rate': 0.18770062227924292, 'subsample': 0.9099971459455695, 'colsample_bytree': 0.5951991591471872, 'min_child_weight': 14, 'gamma': 1.6491795072430988, 'reg_lambda': 18.843499171794203, 'reg_alpha': 14.1165725608851}. Best is trial 22 with value: 3.8464348316192627.
🏃 View run dazzling-conch-571 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/19a81813adc141fc8197cf096b3d8ece
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:16:11,957] Trial 26 finished with value: 3.881455326080322 and parameters: {'n_estimators': 413, 'max_depth': 19, 'learning_rate': 0.3141567250600783, 'subsample': 0.8883507842411266, 'colsample_bytree': 0.7157189475221554, 'min_child_weight': 13, 'gamma': 1.168250056995761, 'reg_lambda': 16.113505217310504, 'reg_alpha': 8.430002692386486}. Best is trial 22 with value: 3.8464348316192627.
🏃 View run bright-midge-862 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/2041781b29904f7babf20b4ab03c53a7
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:16:16,959] Trial 27 finished with value: 3.8295311450958254 and parameters: {'n_estimators': 415, 'max_depth': 20, 'learning_rate': 0.29263456258035475, 'subsample': 0.8759669065136347, 'colsample_bytree': 0.7213914971809194, 'min_child_weight': 17, 'gamma': 1.0059958323704052, 'reg_lambda': 37.94112216359326, 'reg_alpha': 0.5695261402488025}. Best is trial 27 with value: 3.8295311450958254.
🏃 View run smiling-tern-522 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/a62c4bb390a74704aedd2f65853f684e
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:16:21,962] Trial 28 finished with value: 3.962916898727417 and parameters: {'n_estimators': 244, 'max_depth': 25, 'learning_rate': 0.2649784097052328, 'subsample': 0.9452206609751908, 'colsample_bytree': 0.8094479790645572, 'min_child_weight': 18, 'gamma': 2.09721468460627, 'reg_lambda': 36.553991892112094, 'reg_alpha': 22.15749304929752}. Best is trial 27 with value: 3.8295311450958254.
🏃 View run bright-wolf-118 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/f5fa2047d2034587a301d34d505d91ec
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4

2026/03/08 17:18:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/08 17:18:29 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/d77f94d166234d1fa0501bcdd29ff5e4
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4

In [36]:
study.best_params

{'n_estimators': 415,
 'max_depth': 20,
 'learning_rate': 0.29263456258035475,
 'subsample': 0.8759669065136347,
 'colsample_bytree': 0.7213914971809194,
 'min_child_weight': 17,
 'gamma': 1.0059958323704052,
 'reg_lambda': 37.94112216359326,
 'reg_alpha': 0.5695261402488025}

In [29]:
study.best_value

3.8295311450958254

In [ ]:
study.best_value

3.8787633895874025

In [35]:
# optimization history plot
optuna.visualization.plot_optimization_history(study)

In [37]:
# plot hyperparameter importance plot
optuna.visualization.plot_param_importances(study)

In [38]:
# slice plot
optuna.visualization.plot_slice(study)

# LGBM HP Tuning

In [39]:
def objective_lgbm(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators",10,500),
            "max_depth": trial.suggest_int("max_depth",1,40),
            "learning_rate": trial.suggest_float("learning_rate",0.1,0.8),
            "subsample": trial.suggest_float("subsample",0.5,1),
            "min_child_weight": trial.suggest_int("min_child_weight",5,20),
            "min_split_gain": trial.suggest_float("min_split_gain",0,10),
            "reg_lambda": trial.suggest_float("reg_lambda",0,100),
            "random_state": 42,
            "n_jobs": -1,
        }

        # log model parameters
        mlflow.log_params(params)

        xgb_reg = LGBMRegressor(**params)
        model = TransformedTargetRegressor(regressor=xgb_reg,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())
        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [40]:
# create optuna study
study_lgbm = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study_lgbm.optimize(objective_lgbm,n_trials=30,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study_lgbm.best_params)

    # log the best score
    mlflow.log_metric("best_score",study_lgbm.best_value)

    # train the model on best parameters
    best_lgbm = LGBMRegressor(**study_lgbm.best_params)

    best_lgbm.fit(X_train_trans,y_train_pt.values.ravel())

    # get the predictions
    y_pred_train = best_lgbm.predict(X_train_trans)
    y_pred_test = best_lgbm.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_lgbm,
                                        transformer=pt)


    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_lgbm,artifact_path="model")

[I 2026-03-08 17:22:37,868] A new study created in memory with name: no-name-3dfe9b3d-ba21-4456-920a-2e0ed8968e7e

  0%|          | 0/30 [00:00<?, ?it/s]

🏃 View run thoughtful-fox-418 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/86902510bd03499f9d973192d82534dd
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:22:47,368] Trial 1 finished with value: 4.102902325912611 and parameters: {'n_estimators': 28, 'max_depth': 5, 'learning_rate': 0.5422272190410119, 'subsample': 0.9893259576137438, 'min_child_weight': 15, 'min_split_gain': 1.2514371731536522, 'reg_lambda': 28.866438725329367}. Best is trial 1 with value: 4.102902325912611.
🏃 View run clumsy-fox-416 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/40579f53575e4b46949e2f1fc1b645e5
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:22:47,579] Trial 0 finished with value: 4.212433577341244 and parameters: {'n_estimators': 254, 'max_depth': 5, 'learning_rate': 0.6569909245468069, 'subsample': 0.9648791939930522, 'min_child_weight': 6, 'min_split_gain': 7.699873940843922, 'reg_lambda': 13.59907727755324}. Best is trial 1 with value: 4.102902325912611.
🏃 View run unique-trout-748 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/a00577a1e3e94888814d20b732e6f5cf
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:22:52,731] Trial 3 finished with value: 4.158382496697004 and parameters: {'n_estimators': 23, 'max_depth': 13, 'learning_rate': 0.41519603292454, 'subsample': 0.7372729515036944, 'min_child_weight': 7, 'min_split_gain': 8.397623462362827, 'reg_lambda': 69.06504777109606}. Best is trial 1 with value: 4.102902325912611.
🏃 View run flawless-lark-605 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/9fef6374b66f46dbb467df9bac2f125f
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:22:53,191] Trial 2 finished with value: 4.126347760998658 and parameters: {'n_estimators': 284, 'max_depth': 13, 'learning_rate': 0.2422410485042277, 'subsample': 0.8999910011093892, 'min_child_weight': 12, 'min_split_gain': 5.943246785299898, 'reg_lambda': 56.59244107806744}. Best is trial 1 with value: 4.102902325912611.
🏃 View run placid-shad-351 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/25f3202a3fba40de86b86b497159c5d5
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:04,604] Trial 5 finished with value: 4.144336174035082 and parameters: {'n_estimators': 13, 'max_depth': 17, 'learning_rate': 0.7241590993693641, 'subsample': 0.8322547880744801, 'min_child_weight': 19, 'min_split_gain': 4.641731589659418, 'reg_lambda': 25.440130688434458}. Best is trial 1 with value: 4.102902325912611.
🏃 View run judicious-perch-74 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/8a094904a56e4a8c8eb692f4a0a15828
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:05,032] Trial 4 finished with value: 4.118791263122329 and parameters: {'n_estimators': 458, 'max_depth': 9, 'learning_rate': 0.2376569641465365, 'subsample': 0.843727796299857, 'min_child_weight': 10, 'min_split_gain': 7.59370772632746, 'reg_lambda': 5.919196141984251}. Best is trial 1 with value: 4.102902325912611.
🏃 View run rare-mule-205 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/d2e3465c35fb4d50b4e58d56180d15bd
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:09,174] Trial 6 finished with value: 4.153346470756335 and parameters: {'n_estimators': 59, 'max_depth': 24, 'learning_rate': 0.2949227926689629, 'subsample': 0.9366789186312764, 'min_child_weight': 11, 'min_split_gain': 8.117277684377335, 'reg_lambda': 83.5655880111673}. Best is trial 1 with value: 4.102902325912611.
🏃 View run languid-goat-30 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/65846a25bdda4b7183fc2139761ef568
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:14,195] Trial 7 finished with value: 4.119991886119868 and parameters: {'n_estimators': 125, 'max_depth': 37, 'learning_rate': 0.23057373182925123, 'subsample': 0.8090782910432344, 'min_child_weight': 19, 'min_split_gain': 6.127697366880841, 'reg_lambda': 38.52853353759696}. Best is trial 1 with value: 4.102902325912611.
🏃 View run angry-rat-573 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/93a0feb9b7d541f9bb54a44e201a9f54
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:19,168] Trial 8 finished with value: 4.165399935672478 and parameters: {'n_estimators': 198, 'max_depth': 18, 'learning_rate': 0.4510624789923616, 'subsample': 0.7009542919025755, 'min_child_weight': 20, 'min_split_gain': 9.736193186046545, 'reg_lambda': 67.4885384088053}. Best is trial 1 with value: 4.102902325912611.
🏃 View run rare-fly-217 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/b659fe1338e7458bbe2ceed30938b901
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:24,197] Trial 9 finished with value: 4.078065819082708 and parameters: {'n_estimators': 417, 'max_depth': 23, 'learning_rate': 0.4488674395802479, 'subsample': 0.7214590175046327, 'min_child_weight': 8, 'min_split_gain': 3.7570422955968885, 'reg_lambda': 84.76859959890209}. Best is trial 9 with value: 4.078065819082708.
🏃 View run spiffy-bug-258 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/6eca2a4f92bf47ae8bc34628f9d7b163
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:29,662] Trial 10 finished with value: 4.01586430318717 and parameters: {'n_estimators': 122, 'max_depth': 11, 'learning_rate': 0.12476577573084303, 'subsample': 0.704861156850482, 'min_child_weight': 19, 'min_split_gain': 1.210516504558723, 'reg_lambda': 52.18592397128544}. Best is trial 10 with value: 4.01586430318717.
🏃 View run casual-finch-492 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/d3bbdb1d4bce4cdaa01e4921d23df6d6
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:35,208] Trial 11 finished with value: 4.101179234021947 and parameters: {'n_estimators': 491, 'max_depth': 28, 'learning_rate': 0.5941651541088925, 'subsample': 0.5676349659701531, 'min_child_weight': 8, 'min_split_gain': 2.512590636046949, 'reg_lambda': 99.8804449041607}. Best is trial 10 with value: 4.01586430318717.
🏃 View run legendary-perch-194 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/8f0b08e92e56441ab9754e2780937871
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
🏃 View run wistful-newt-966 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/7e469f6b787c41c7909f3926f345cd56
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:23:56,980] Trial 13 finished with value: 3.9066127474595094 and parameters: {'n_estimators': 426, 'max_depth': 31, 'learning_rate': 0.11403942880205875, 'subsample': 0.6437269095433559, 'min_child_weight': 15, 'min_split_gain': 0.0805650116196659, 'reg_lambda': 95.72533371431881}. Best is trial 13 with value: 3.9066127474595094.
[I 2026-03-08 17:23:56,986] Trial 12 finished with value: 4.043042772184946 and parameters: {'n_estimators': 436, 'max_depth': 27, 'learning_rate': 0.10084506362969037, 'subsample': 0.5844359113463848, 'min_child_weight': 15, 'min_split_gain': 1.7164243027781063, 'reg_lambda': 94.75539568842251}. Best is trial 13 with value: 3.9066127474595094.
🏃 View run righteous-skink-413 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/44f4fe9d34df4377977189f268d86079
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:20,534] Trial 14 finished with value: 3.9328115001196173 and parameters: {'n_estimators': 359, 'max_depth': 35, 'learning_rate': 0.10916124459106918, 'subsample': 0.6435350746088573, 'min_child_weight': 16, 'min_split_gain': 0.3048643739140946, 'reg_lambda': 44.94686439964049}. Best is trial 13 with value: 3.9066127474595094.
🏃 View run suave-mink-783 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/7f89eae74b164263a7d49bd780cf0eb5
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:20,778] Trial 15 finished with value: 3.8429753760472574 and parameters: {'n_estimators': 329, 'max_depth': 35, 'learning_rate': 0.11014692783856105, 'subsample': 0.6379973849967436, 'min_child_weight': 16, 'min_split_gain': 0.01005294417120095, 'reg_lambda': 58.22261231372337}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run smiling-shrew-792 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/a293ef4ba24a4bd1ae96ea224f782080
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:33,778] Trial 16 finished with value: 3.8860164437197717 and parameters: {'n_estimators': 359, 'max_depth': 32, 'learning_rate': 0.3480556748455633, 'subsample': 0.511900327795562, 'min_child_weight': 17, 'min_split_gain': 0.03523820560535748, 'reg_lambda': 71.29787120790755}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run polite-snipe-691 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/621706ac0d8c49fb83a83511b7ffaabb
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:33,958] Trial 17 finished with value: 3.9527078274614573 and parameters: {'n_estimators': 348, 'max_depth': 32, 'learning_rate': 0.347980920508745, 'subsample': 0.5131587084512064, 'min_child_weight': 16, 'min_split_gain': 0.27557951699715555, 'reg_lambda': 68.83620101740115}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run adventurous-rook-979 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/69f682b9402e44ae9a7826f4f4235ccc
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
🏃 View run ambitious-conch-547 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/4ec328cd990c4240a38a6c0732e2ab72
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:45,327] Trial 18 finished with value: 4.092247650855609 and parameters: {'n_estimators': 344, 'max_depth': 39, 'learning_rate': 0.5228680537271819, 'subsample': 0.5005628767424862, 'min_child_weight': 17, 'min_split_gain': 2.9330089481917136, 'reg_lambda': 79.91704298065066}. Best is trial 15 with value: 3.8429753760472574.
[I 2026-03-08 17:24:45,358] Trial 19 finished with value: 4.071298541275807 and parameters: {'n_estimators': 346, 'max_depth': 40, 'learning_rate': 0.35985852109549255, 'subsample': 0.5292560995489239, 'min_child_weight': 17, 'min_split_gain': 3.2763276330587074, 'reg_lambda': 59.7269718132535}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run treasured-crow-391 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/d6893e3ff80b4bf18d1813f23a4b232f
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:55,817] Trial 20 finished with value: 4.115145034374336 and parameters: {'n_estimators': 273, 'max_depth': 35, 'learning_rate': 0.7841546572457693, 'subsample': 0.6328715372396068, 'min_child_weight': 14, 'min_split_gain': 1.919365660311704, 'reg_lambda': 42.898368648586484}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run adorable-snake-734 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/f978dac86c8446eb8f44ad5e9b83652d
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:24:56,063] Trial 21 finished with value: 4.0279231391062735 and parameters: {'n_estimators': 272, 'max_depth': 33, 'learning_rate': 0.18478005752600807, 'subsample': 0.6229630838125649, 'min_child_weight': 14, 'min_split_gain': 1.7599748281338592, 'reg_lambda': 42.47910865395713}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run caring-sponge-567 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/0b542e631735479f8dad72aa9fc36885
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:25:09,093] Trial 22 finished with value: 3.885468097598147 and parameters: {'n_estimators': 395, 'max_depth': 29, 'learning_rate': 0.1749029509950567, 'subsample': 0.5852067637260673, 'min_child_weight': 13, 'min_split_gain': 0.04935196281952338, 'reg_lambda': 75.32069166853941}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run bustling-wren-140 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/0f44d13b194d4036af3d35b40570dafa
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:25:26,887] Trial 24 finished with value: 3.9969783634619858 and parameters: {'n_estimators': 394, 'max_depth': 28, 'learning_rate': 0.17061042053714479, 'subsample': 0.5721823663733402, 'min_child_weight': 13, 'min_split_gain': 0.8677309658603675, 'reg_lambda': 78.9758192644639}. Best is trial 15 with value: 3.8429753760472574.
🏃 View run righteous-cod-592 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/00189f91dde449269050ec969e6ab9b6
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:25:27,048] Trial 23 finished with value: 3.8409433389512 and parameters: {'n_estimators': 398, 'max_depth': 30, 'learning_rate': 0.17723976615372525, 'subsample': 0.6668154532640596, 'min_child_weight': 13, 'min_split_gain': 0.00042029710843746043, 'reg_lambda': 75.85847527149905}. Best is trial 23 with value: 3.8409433389512.
🏃 View run invincible-vole-375 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/2c2aa3dccb6a489bb04042852e51b810
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:25:41,613] Trial 25 finished with value: 4.093102983677613 and parameters: {'n_estimators': 302, 'max_depth': 24, 'learning_rate': 0.18889567011695, 'subsample': 0.672177246581241, 'min_child_weight': 10, 'min_split_gain': 4.033046507447157, 'reg_lambda': 60.98843469647912}. Best is trial 23 with value: 3.8409433389512.
🏃 View run silent-ox-394 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/46f571c130d44ceb8319032792fabc59
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:25:41,993] Trial 26 finished with value: 4.054030686572273 and parameters: {'n_estimators': 311, 'max_depth': 24, 'learning_rate': 0.20395624630565654, 'subsample': 0.6749716671959353, 'min_child_weight': 10, 'min_split_gain': 2.2872626650338033, 'reg_lambda': 58.30688124122984}. Best is trial 23 with value: 3.8409433389512.
🏃 View run auspicious-stoat-869 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/e759a5db5a86427c9565e515c67040ff
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
🏃 View run peaceful-newt-10 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/3820b4e046684eefbc9b50b01f471674
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:25:52,590] Trial 27 finished with value: 4.062920271864883 and parameters: {'n_estimators': 390, 'max_depth': 29, 'learning_rate': 0.29391486376844367, 'subsample': 0.5912765235931207, 'min_child_weight': 12, 'min_split_gain': 2.473381489109012, 'reg_lambda': 87.53080503137848}. Best is trial 23 with value: 3.8409433389512.
[I 2026-03-08 17:25:52,626] Trial 28 finished with value: 4.014507595008795 and parameters: {'n_estimators': 227, 'max_depth': 29, 'learning_rate': 0.29339965942334717, 'subsample': 0.7848511266050445, 'min_child_weight': 12, 'min_split_gain': 1.024238080911231, 'reg_lambda': 90.03009538915515}. Best is trial 23 with value: 3.8409433389512.
🏃 View run polite-jay-201 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/225fca704f0a44acbceaf39d7c8479a5
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 17:26:02,893] Trial 29 finished with value: 3.9912123032745654 and parameters: {'n_estimators': 479, 'max_depth': 20, 'learning_rate': 0.1491107776091538, 'subsample': 0.7659894831037082, 'min_child_weight': 13, 'min_split_gain': 0.8656713942974065, 'reg_lambda': 77.33084449950802}. Best is trial 23 with value: 3.8409433389512.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002791 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 93
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 23
[LightGBM] [Info] Start training from score -0.000000

2026/03/08 17:26:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/08 17:26:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/2625240f7ef041889a70c3cbe6810794
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4

In [42]:
study_lgbm.best_params

{'n_estimators': 398,
 'max_depth': 30,
 'learning_rate': 0.17723976615372525,
 'subsample': 0.6668154532640596,
 'min_child_weight': 13,
 'min_split_gain': 0.00042029710843746043,
 'reg_lambda': 75.85847527149905}

In [ ]:
study_lgbm.best_params

{'n_estimators': 152,
 'max_depth': 19,
 'learning_rate': 0.7444003876852524,
 'subsample': 0.5284402935634638,
 'min_child_weight': 9,
 'min_split_gain': 0.014263522429579317,
 'reg_lambda': 55.54275117208787}

In [41]:
study_lgbm.best_value

3.8409433389512

In [ ]:
study_lgbm.best_value

3.9072908835002678

In [43]:
# optimization history plot
optuna.visualization.plot_optimization_history(study_lgbm)

In [44]:
# plot hyperparameter importance plot
optuna.visualization.plot_param_importances(study_lgbm)

In [45]:
# slice plot
optuna.visualization.plot_slice(study_lgbm)

# RF HP Tuning

In [63]:
def objective_rf(trial):
    with mlflow.start_run(nested=True):
        params = {
                  "n_estimators": trial.suggest_int("n_estimators", 100, 800),

                  "max_depth": trial.suggest_int("max_depth", 3, 20),

                  "max_features": trial.suggest_categorical(
                      "max_features",
                      ["sqrt", "log2", None]
                  ),

                  "min_samples_split": trial.suggest_int(
                      "min_samples_split",
                      2,
                      10
                  ),

                  "min_samples_leaf": trial.suggest_int(
                      "min_samples_leaf",
                      1,
                      10
                  ),

                  "max_samples": trial.suggest_float(
                      "max_samples",
                      0.7,
                      1.0
                  ),



                  "random_state": 42,
                  "n_jobs": -1,
              }

        # log model parameters
        mlflow.log_params(params)

        # build the model
        rf = RandomForestRegressor(**params)
        model = TransformedTargetRegressor(regressor=rf,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())

        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [64]:
# create optuna study
study_rf = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study_rf.optimize(objective_rf,n_trials=20,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study_rf.best_params)

    # log the best score
    mlflow.log_metric("best_score",study_rf.best_value)

    # train the model on best parameters
    best_rf = RandomForestRegressor(**study_rf.best_params)

    best_rf.fit(X_train_trans,y_train_pt.values.ravel())

    # get the predictions
    y_pred_train = best_rf.predict(X_train_trans)
    y_pred_test = best_rf.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_rf,transformer=pt)


    scores = cross_val_score(model,X_train_trans,y_train,scoring="neg_mean_absolute_error",cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    mlflow.sklearn.log_model(best_rf,artifact_path="model")

[I 2026-03-08 18:11:36,001] A new study created in memory with name: no-name-3edc6fe1-07ed-499d-bfbd-dbf30d387b5c

  0%|          | 0/20 [00:00<?, ?it/s]

🏃 View run delicate-fly-720 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/e601e7e77ada40a888d120a5810ceaa9
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:12:31,034] Trial 0 finished with value: 5.065500006708376 and parameters: {'n_estimators': 681, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_samples': 0.7208174358150577}. Best is trial 0 with value: 5.065500006708376.
🏃 View run likeable-owl-295 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/85631e4308fe4353a514f2e0b2211ea4
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:12:31,986] Trial 1 finished with value: 4.184766482267713 and parameters: {'n_estimators': 212, 'max_depth': 7, 'max_features': None, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_samples': 0.8158629662904184}. Best is trial 1 with value: 4.184766482267713.
🏃 View run delightful-sheep-178 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/f77f9ba72fe143f1a35427c36dafc9da
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:12:44,524] Trial 2 finished with value: 5.520736147194271 and parameters: {'n_estimators': 282, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_samples': 0.7763063441523254}. Best is trial 1 with value: 4.184766482267713.
🏃 View run upbeat-squirrel-47 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/b52db3af157346cfa930b37b4f66518a
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:12:52,613] Trial 3 finished with value: 4.017305838350035 and parameters: {'n_estimators': 130, 'max_depth': 16, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_samples': 0.8792030359898477}. Best is trial 3 with value: 4.017305838350035.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run respected-chimp-850 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/c0748a3a57804e94a39abad221eb76f2
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:14:56,839] Trial 4 finished with value: 5.2956144060849395 and parameters: {'n_estimators': 747, 'max_depth': 3, 'max_features': None, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_samples': 0.9664911660201392}. Best is trial 3 with value: 4.017305838350035.
🏃 View run melodic-crab-647 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/81fc7b4d50b94ea190db3681783517b0
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:15:03,814] Trial 5 finished with value: 3.909053712144041 and parameters: {'n_estimators': 574, 'max_depth': 15, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.7735378467772677}. Best is trial 5 with value: 3.909053712144041.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run merciful-vole-28 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/caa99f6cfe9f4672be2df4edec8d3c4c
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:15:12,787] Trial 6 finished with value: 4.358558322188214 and parameters: {'n_estimators': 125, 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_samples': 0.8512377624869194}. Best is trial 5 with value: 3.909053712144041.
🏃 View run unequaled-gnat-879 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/516f48183b75480cbdae1efcbac59bd6
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:15:26,812] Trial 7 finished with value: 4.000693590643779 and parameters: {'n_estimators': 144, 'max_depth': 12, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.8338788301106099}. Best is trial 5 with value: 3.909053712144041.
🏃 View run charming-owl-893 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/f51762b53a8c4e69b2b0771895abdab9
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:16:07,047] Trial 9 finished with value: 4.02488713095219 and parameters: {'n_estimators': 186, 'max_depth': 11, 'max_features': 'sqrt', 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_samples': 0.9029296665012222}. Best is trial 5 with value: 3.909053712144041.
🏃 View run sassy-dog-450 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/bf9bcc07183a4ac6bb3df5f1691b702d
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:16:12,366] Trial 8 finished with value: 4.2208137727396435 and parameters: {'n_estimators': 636, 'max_depth': 8, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_samples': 0.7636264345479159}. Best is trial 5 with value: 3.909053712144041.
🏃 View run dashing-bird-434 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/c221c90b737c4d179892fc318076e115
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:17:29,372] Trial 10 finished with value: 4.026344379775517 and parameters: {'n_estimators': 486, 'max_depth': 13, 'max_features': 'log2', 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_samples': 0.9586773970982404}. Best is trial 5 with value: 3.909053712144041.
🏃 View run nebulous-wasp-710 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/5826ae3f37dc42f3aa1ac24f1a71bd2c
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:17:30,159] Trial 11 finished with value: 3.945905786357013 and parameters: {'n_estimators': 491, 'max_depth': 20, 'max_features': 'log2', 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_samples': 0.7007921934889734}. Best is trial 5 with value: 3.909053712144041.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run mysterious-elk-79 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/9278ca3ad5044f51b1bfb9a96381518c
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:19:09,497] Trial 13 finished with value: 3.9410889860153793 and parameters: {'n_estimators': 444, 'max_depth': 20, 'max_features': 'log2', 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_samples': 0.7032052919516979}. Best is trial 5 with value: 3.909053712144041.
🏃 View run unleashed-sponge-588 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/b1a06a7eafeb4600b4d61849168630a3
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:19:16,539] Trial 12 finished with value: 3.8936227482344514 and parameters: {'n_estimators': 427, 'max_depth': 19, 'max_features': 'log2', 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_samples': 0.8033410255656028}. Best is trial 12 with value: 3.8936227482344514.

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

🏃 View run awesome-bat-811 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/b2ac2569e9b248bbb477d0634f5574f4
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:20:52,966] Trial 14 finished with value: 3.884512455965713 and parameters: {'n_estimators': 378, 'max_depth': 20, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_samples': 0.7531529960526339}. Best is trial 14 with value: 3.884512455965713.
🏃 View run blushing-sloth-445 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/091089b405f747629edf996271ba0dc9
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:21:01,118] Trial 15 finished with value: 3.8971080553177573 and parameters: {'n_estimators': 399, 'max_depth': 17, 'max_features': 'log2', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_samples': 0.7775093401117528}. Best is trial 14 with value: 3.884512455965713.
🏃 View run zealous-cow-869 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/5230c4a37dd647d8949525bd5bf5ff01
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:22:03,342] Trial 16 finished with value: 3.9111549551864373 and parameters: {'n_estimators': 357, 'max_depth': 18, 'max_features': 'log2', 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_samples': 0.8032358706952992}. Best is trial 14 with value: 3.884512455965713.
🏃 View run clean-doe-228 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/980bf947bbac416aa39b396fc620236c
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:22:03,774] Trial 17 finished with value: 3.922352068385378 and parameters: {'n_estimators': 337, 'max_depth': 18, 'max_features': 'log2', 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_samples': 0.7448067701837314}. Best is trial 14 with value: 3.884512455965713.
🏃 View run brawny-ray-105 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/c9378ee793804b18b896d3dbf0898c16
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:24:20,416] Trial 18 finished with value: 3.8167487936424123 and parameters: {'n_estimators': 307, 'max_depth': 19, 'max_features': None, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_samples': 0.7429771337433382}. Best is trial 18 with value: 3.8167487936424123.
🏃 View run awesome-owl-519 at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/20105a1e112344ec8eaf2378c33fc397
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4
[I 2026-03-08 18:26:09,886] Trial 19 finished with value: 3.807369054223122 and parameters: {'n_estimators': 539, 'max_depth': 14, 'max_features': None, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_samples': 0.9188618214071786}. Best is trial 19 with value: 3.807369054223122.

2026/03/08 18:28:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/08 18:29:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4/runs/2b7dd844a7574cb09ac8db9d7c387763
🧪 View experiment at: https://dagshub.com/Iamkartikey44/Food_Delivery_Time_Prediction.mlflow/#/experiments/4

In [65]:
study_rf.best_params #old

{'n_estimators': 539,
 'max_depth': 14,
 'max_features': None,
 'min_samples_split': 5,
 'min_samples_leaf': 5,
 'max_samples': 0.9188618214071786}

In [59]:
study_rf.best_params

{'n_estimators': 500,
 'max_depth': 14,
 'max_features': None,
 'min_samples_split': 9,
 'min_samples_leaf': 6,
 'max_samples': 0.9797814656591307}

In [67]:
study_rf.best_value

3.807369054223122

In [68]:
study_rf.best_value #OLD

3.807369054223122

In [61]:
# optimization history plot
optuna.visualization.plot_optimization_history(study_rf)

In [62]:
# plot hyperparameter importance plot
optuna.visualization.plot_param_importances(study_rf)

In [53]:
# slice plot
optuna.visualization.plot_slice(study_rf)